#!/bin/sh -e

PREFIX="/usr"
DAEMON_ARGS=""

if [ -e /etc/bytestagd/bytestagd.sh ]; then
    . /etc/bytestagd/bytestagd.sh
fi

PYTHONPATH=$PYTHONPATH

export PYTHONPATH

if [ "$USE_USER" -a "$USE_GROUP" ]; then
    sudo -u "$USE_USER" -g "$USE_GROUP" PYTHONPATH=$PYTHONPATH python3 -m bytestag $DAEMON_ARGS
else
    python3 -m bytestag $DAEMON_ARGS
fi
